# Generated by Django 5.1.7 on 2025-06-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyhosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Folha de Pagamento', 'Folha de Pagamento'), ('Contas', 'Contas (Luz, Água, Internet)'), ('Suprimentos e Limpeza', 'Suprimentos e Limpeza'), ('Manutenção e Reparos', 'Manutenção e Reparos'), ('Impostos e Taxas', 'Impostos e Taxas'), ('Equipamentos e Móveis', 'Equipamentos e Móveis'), ('Serviços Terceirizados', 'Serviços Terceirizados'), ('Deslocamentos e Transporte', 'Deslocamentos e Transporte'), ('Multas e Encargos', 'Multas e Encargos'), ('Outros', 'Outros')], max_length=30)),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Pix', 'Pix'), ('Transferência Bancária', 'Transferência Bancária'), ('Boleto', 'Boleto'), ('Outros', 'Outros')], max_length=25)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsavel', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'db_table': 'despesa',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Diária', 'Diária'), ('Frigobar', 'Frigobar'), ('Estacionamento', 'Estacionamento'), ('Lavanderia', 'Lavanderia'), ('Taxa Extra', 'Taxa Extra'), ('Outro', 'Outro')], max_length=20)),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Pix', 'Pix'), ('Transferência Bancária', 'Transferência Bancária'), ('Boleto', 'Boleto'), ('Outros', 'Outros')], max_length=25)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyhosts.quarto')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'receita',
            },
        ),
    ]
