# Generated by Django 5.1.7 on 2025-06-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyhosts', '0002_despesa_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('financeiro', 'Financeiro'), ('operacional', 'Operacional'), ('hospedes', 'Hóspedes'), ('manutencao', 'Manutenção'), ('outro', 'Outro')], max_length=20)),
                ('responsavel', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'db_table': 'relatorio',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
