# Generated by Django 5.1.7 on 2025-06-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyhosts', '0003_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data_criacao',
            field=models.DateField(),
        ),
    ]
